-- -----------------------------------------------------
-- Table "LIB_AUTHORS"
-- -----------------------------------------------------
CREATE TABLE LIB_AUTHORS (
  "AUT_ID" INT PRIMARY KEY NOT NULL,
  "AUT_FIRST_NAME" VARCHAR(30) NOT NULL,
  "AUT_LAST_NAME" VARCHAR(30) NOT NULL,
  "AUT_DATE_DOB" DATE NOT NULL,
  "AUT_GENDER" VARCHAR(1) NOT NULL,
  "AUT_CONTACT" VARCHAR(30) NOT NULL,
  "AUT_OTHER_DETAILS" VARCHAR(200) NOT NULL);


-- -----------------------------------------------------
-- Table "LIB_BOOK_CATEGORIES"
-- -----------------------------------------------------
CREATE TABLE LIB_BOOK_CATEGORIES (
  "CAT_ID" INT PRIMARY KEY NOT NULL,
  "CAT_DESCRIPCIÓN" VARCHAR(60) NOT NULL);


-- -----------------------------------------------------
-- Table "LIB_BOOKS"
-- -----------------------------------------------------
CREATE TABLE LIB_BOOKS (
  "BOOK_ID" INT PRIMARY KEY NOT NULL,
  "BOOK_AUT_ID" INT NOT NULL,
  "BOOK_CAT_ID" INT NOT NULL,
  "BOOK_ISBN" VARCHAR(15) NOT NULL,
  "BOOK_PUBLISHED_DATE" DATE NOT NULL,
  "BOOK_TITLE" VARCHAR(100) NOT NULL,
  "BOOK_PRICE" DECIMAL(8,2) NULL NULL,
  "BOOK_DESCRIPCIÓN" VARCHAR(100) NOT NULL,
  "BOOK_MIMETYPE" VARCHAR(400) NOT NULL,
  "BOOK_FILENAME" VARCHAR(400) NOT NULL,
  "BOOK_IMAGE_LAST_UPDATE" TIMESTAMP NOT NULL,
  CONSTRAINT "FK_LIB_AUTHORS"
    FOREIGN KEY ("BOOK_AUT_ID")
    REFERENCES LIB_AUTHORS ("AUT_ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "FK_LIB_BOOK_CATEGORIES"
    FOREIGN KEY ("BOOK_CAT_ID")
    REFERENCES LIB_BOOK_CATEGORIES ("CAT_ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);